name: Release
on:
 pull_request:
    types:
      - closed
    branches:
      - master
      - develop
 
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true
    steps:
 
      - name: Checkout source code
        uses: actions/checkout@v2
 
      - name: Change Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.0'
 
      - name: Install
        run: npm install
 

      - name: Pre-release or Release
        run: ./cli.js project release --npm-publish --yes --dry-run
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  update:
    name: Update Develop
    if: github.ref == 'master'
    needs: release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Develop Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git status
          git fetch --unshallow
        
          git checkout develop
          git pull
          git pull origin master
          git push